// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/routing_enums.proto

#include "ortools/constraint_solver/routing_enums.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace operations_research {
PROTOBUF_CONSTEXPR FirstSolutionStrategy::FirstSolutionStrategy(
    ::_pbi::ConstantInitialized) {}
struct FirstSolutionStrategyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FirstSolutionStrategyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FirstSolutionStrategyDefaultTypeInternal() {}
  union {
    FirstSolutionStrategy _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FirstSolutionStrategyDefaultTypeInternal _FirstSolutionStrategy_default_instance_;
PROTOBUF_CONSTEXPR LocalSearchMetaheuristic::LocalSearchMetaheuristic(
    ::_pbi::ConstantInitialized) {}
struct LocalSearchMetaheuristicDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LocalSearchMetaheuristicDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LocalSearchMetaheuristicDefaultTypeInternal() {}
  union {
    LocalSearchMetaheuristic _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LocalSearchMetaheuristicDefaultTypeInternal _LocalSearchMetaheuristic_default_instance_;
}  // namespace operations_research
static ::_pb::Metadata file_level_metadata_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto = nullptr;

const uint32_t TableStruct_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::operations_research::FirstSolutionStrategy, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::operations_research::LocalSearchMetaheuristic, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::operations_research::FirstSolutionStrategy)},
  { 6, -1, -1, sizeof(::operations_research::LocalSearchMetaheuristic)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::operations_research::_FirstSolutionStrategy_default_instance_._instance,
  &::operations_research::_LocalSearchMetaheuristic_default_instance_._instance,
};

const char descriptor_table_protodef_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n-ortools/constraint_solver/routing_enum"
  "s.proto\022\023operations_research\"\257\003\n\025FirstSo"
  "lutionStrategy\"\225\003\n\005Value\022\t\n\005UNSET\020\000\022\r\n\tA"
  "UTOMATIC\020\017\022\025\n\021PATH_CHEAPEST_ARC\020\003\022\035\n\031PAT"
  "H_MOST_CONSTRAINED_ARC\020\004\022\026\n\022EVALUATOR_ST"
  "RATEGY\020\005\022\013\n\007SAVINGS\020\n\022\t\n\005SWEEP\020\013\022\020\n\014CHRI"
  "STOFIDES\020\r\022\023\n\017ALL_UNPERFORMED\020\006\022\022\n\016BEST_"
  "INSERTION\020\007\022\037\n\033PARALLEL_CHEAPEST_INSERTI"
  "ON\020\010\022!\n\035SEQUENTIAL_CHEAPEST_INSERTION\020\016\022"
  "\034\n\030LOCAL_CHEAPEST_INSERTION\020\t\022!\n\035LOCAL_C"
  "HEAPEST_COST_INSERTION\020\020\022\027\n\023GLOBAL_CHEAP"
  "EST_ARC\020\001\022\026\n\022LOCAL_CHEAPEST_ARC\020\002\022\033\n\027FIR"
  "ST_UNBOUND_MIN_VALUE\020\014\"\256\001\n\030LocalSearchMe"
  "taheuristic\"\221\001\n\005Value\022\t\n\005UNSET\020\000\022\r\n\tAUTO"
  "MATIC\020\006\022\022\n\016GREEDY_DESCENT\020\001\022\027\n\023GUIDED_LO"
  "CAL_SEARCH\020\002\022\027\n\023SIMULATED_ANNEALING\020\003\022\017\n"
  "\013TABU_SEARCH\020\004\022\027\n\023GENERIC_TABU_SEARCH\020\005B"
  "I\n#com.google.ortools.constraintsolverP\001"
  "\252\002\037Google.OrTools.ConstraintSolverb\006prot"
  "o3"
  ;
static ::_pbi::once_flag descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto = {
    false, false, 762, descriptor_table_protodef_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto,
    "ortools/constraint_solver/routing_enums.proto",
    &descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto::offsets,
    file_level_metadata_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto, file_level_enum_descriptors_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto,
    file_level_service_descriptors_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto_getter() {
  return &descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto(&descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto);
namespace operations_research {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FirstSolutionStrategy_Value_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto);
  return file_level_enum_descriptors_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto[0];
}
bool FirstSolutionStrategy_Value_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::UNSET;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::AUTOMATIC;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::PATH_CHEAPEST_ARC;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::PATH_MOST_CONSTRAINED_ARC;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::EVALUATOR_STRATEGY;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::SAVINGS;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::SWEEP;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::CHRISTOFIDES;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::ALL_UNPERFORMED;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::BEST_INSERTION;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::PARALLEL_CHEAPEST_INSERTION;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::SEQUENTIAL_CHEAPEST_INSERTION;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::LOCAL_CHEAPEST_INSERTION;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::LOCAL_CHEAPEST_COST_INSERTION;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::GLOBAL_CHEAPEST_ARC;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::LOCAL_CHEAPEST_ARC;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::FIRST_UNBOUND_MIN_VALUE;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::Value_MIN;
constexpr FirstSolutionStrategy_Value FirstSolutionStrategy::Value_MAX;
constexpr int FirstSolutionStrategy::Value_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LocalSearchMetaheuristic_Value_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto);
  return file_level_enum_descriptors_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto[1];
}
bool LocalSearchMetaheuristic_Value_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr LocalSearchMetaheuristic_Value LocalSearchMetaheuristic::UNSET;
constexpr LocalSearchMetaheuristic_Value LocalSearchMetaheuristic::AUTOMATIC;
constexpr LocalSearchMetaheuristic_Value LocalSearchMetaheuristic::GREEDY_DESCENT;
constexpr LocalSearchMetaheuristic_Value LocalSearchMetaheuristic::GUIDED_LOCAL_SEARCH;
constexpr LocalSearchMetaheuristic_Value LocalSearchMetaheuristic::SIMULATED_ANNEALING;
constexpr LocalSearchMetaheuristic_Value LocalSearchMetaheuristic::TABU_SEARCH;
constexpr LocalSearchMetaheuristic_Value LocalSearchMetaheuristic::GENERIC_TABU_SEARCH;
constexpr LocalSearchMetaheuristic_Value LocalSearchMetaheuristic::Value_MIN;
constexpr LocalSearchMetaheuristic_Value LocalSearchMetaheuristic::Value_MAX;
constexpr int LocalSearchMetaheuristic::Value_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class FirstSolutionStrategy::_Internal {
 public:
};

FirstSolutionStrategy::FirstSolutionStrategy(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:operations_research.FirstSolutionStrategy)
}
FirstSolutionStrategy::FirstSolutionStrategy(const FirstSolutionStrategy& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  FirstSolutionStrategy* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:operations_research.FirstSolutionStrategy)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FirstSolutionStrategy::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FirstSolutionStrategy::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata FirstSolutionStrategy::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto_getter, &descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto_once,
      file_level_metadata_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto[0]);
}

// ===================================================================

class LocalSearchMetaheuristic::_Internal {
 public:
};

LocalSearchMetaheuristic::LocalSearchMetaheuristic(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:operations_research.LocalSearchMetaheuristic)
}
LocalSearchMetaheuristic::LocalSearchMetaheuristic(const LocalSearchMetaheuristic& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  LocalSearchMetaheuristic* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:operations_research.LocalSearchMetaheuristic)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LocalSearchMetaheuristic::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LocalSearchMetaheuristic::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata LocalSearchMetaheuristic::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto_getter, &descriptor_table_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto_once,
      file_level_metadata_ortools_2fconstraint_5fsolver_2frouting_5fenums_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace operations_research
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::operations_research::FirstSolutionStrategy*
Arena::CreateMaybeMessage< ::operations_research::FirstSolutionStrategy >(Arena* arena) {
  return Arena::CreateMessageInternal< ::operations_research::FirstSolutionStrategy >(arena);
}
template<> PROTOBUF_NOINLINE ::operations_research::LocalSearchMetaheuristic*
Arena::CreateMaybeMessage< ::operations_research::LocalSearchMetaheuristic >(Arena* arena) {
  return Arena::CreateMessageInternal< ::operations_research::LocalSearchMetaheuristic >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
