declare namespace operations_research
{
    declare enum MPSolverResponseStatus
    {
        MPSOLVER_OPTIMAL = 0,
        MPSOLVER_FEASIBLE = 1,
        MPSOLVER_INFEASIBLE = 2,
        MPSOLVER_UNBOUNDED = 3,
        MPSOLVER_ABNORMAL = 4,
        MPSOLVER_NOT_SOLVED = 6,
        MPSOLVER_MODEL_IS_VALID = 97,
        MPSOLVER_CANCELLED_BY_USER = 98,
        MPSOLVER_UNKNOWN_STATUS = 99,
        MPSOLVER_MODEL_INVALID = 5,
        MPSOLVER_MODEL_INVALID_SOLUTION_HINT = 84,
        MPSOLVER_MODEL_INVALID_SOLVER_PARAMETERS = 85,
        MPSOLVER_SOLVER_TYPE_UNAVAILABLE = 7,
        MPSOLVER_INCOMPATIBLE_OPTIONS = 113,
    }

}