// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/packing/vector_bin_packing.proto

#include "ortools/packing/vector_bin_packing.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace operations_research {
namespace packing {
namespace vbp {
PROTOBUF_CONSTEXPR Item::Item(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.resource_usage_)*/{}
  , /*decltype(_impl_._resource_usage_cached_byte_size_)*/{0}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.num_copies_)*/0
  , /*decltype(_impl_.max_number_of_copies_per_bin_)*/0
  , /*decltype(_impl_.penalty_per_missing_copy_)*/0
  , /*decltype(_impl_.num_optional_copies_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ItemDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ItemDefaultTypeInternal() {}
  union {
    Item _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ItemDefaultTypeInternal _Item_default_instance_;
PROTOBUF_CONSTEXPR VectorBinPackingProblem::VectorBinPackingProblem(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.resource_capacity_)*/{}
  , /*decltype(_impl_._resource_capacity_cached_byte_size_)*/{0}
  , /*decltype(_impl_.resource_name_)*/{}
  , /*decltype(_impl_.item_)*/{}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.cost_per_bin_)*/0
  , /*decltype(_impl_.max_bins_)*/0} {}
struct VectorBinPackingProblemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VectorBinPackingProblemDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VectorBinPackingProblemDefaultTypeInternal() {}
  union {
    VectorBinPackingProblem _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VectorBinPackingProblemDefaultTypeInternal _VectorBinPackingProblem_default_instance_;
PROTOBUF_CONSTEXPR VectorBinPackingOneBinInSolution::VectorBinPackingOneBinInSolution(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.item_indices_)*/{}
  , /*decltype(_impl_._item_indices_cached_byte_size_)*/{0}
  , /*decltype(_impl_.item_copies_)*/{}
  , /*decltype(_impl_._item_copies_cached_byte_size_)*/{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VectorBinPackingOneBinInSolutionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VectorBinPackingOneBinInSolutionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VectorBinPackingOneBinInSolutionDefaultTypeInternal() {}
  union {
    VectorBinPackingOneBinInSolution _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VectorBinPackingOneBinInSolutionDefaultTypeInternal _VectorBinPackingOneBinInSolution_default_instance_;
PROTOBUF_CONSTEXPR VectorBinPackingSolution::VectorBinPackingSolution(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.bins_)*/{}
  , /*decltype(_impl_.solver_info_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.objective_value_)*/0
  , /*decltype(_impl_.solve_time_in_seconds_)*/0
  , /*decltype(_impl_.arc_flow_time_in_seconds_)*/0
  , /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VectorBinPackingSolutionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VectorBinPackingSolutionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VectorBinPackingSolutionDefaultTypeInternal() {}
  union {
    VectorBinPackingSolution _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VectorBinPackingSolutionDefaultTypeInternal _VectorBinPackingSolution_default_instance_;
}  // namespace vbp
}  // namespace packing
}  // namespace operations_research
static ::_pb::Metadata file_level_metadata_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto = nullptr;

const uint32_t TableStruct_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::Item, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::Item, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::Item, _impl_.resource_usage_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::Item, _impl_.num_copies_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::Item, _impl_.num_optional_copies_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::Item, _impl_.max_number_of_copies_per_bin_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::Item, _impl_.penalty_per_missing_copy_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingProblem, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingProblem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingProblem, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingProblem, _impl_.resource_capacity_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingProblem, _impl_.resource_name_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingProblem, _impl_.item_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingProblem, _impl_.max_bins_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingProblem, _impl_.cost_per_bin_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingOneBinInSolution, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingOneBinInSolution, _impl_.item_indices_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingOneBinInSolution, _impl_.item_copies_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingSolution, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingSolution, _impl_.solver_info_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingSolution, _impl_.bins_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingSolution, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingSolution, _impl_.objective_value_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingSolution, _impl_.solve_time_in_seconds_),
  PROTOBUF_FIELD_OFFSET(::operations_research::packing::vbp::VectorBinPackingSolution, _impl_.arc_flow_time_in_seconds_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::operations_research::packing::vbp::Item)},
  { 12, 24, -1, sizeof(::operations_research::packing::vbp::VectorBinPackingProblem)},
  { 30, -1, -1, sizeof(::operations_research::packing::vbp::VectorBinPackingOneBinInSolution)},
  { 38, -1, -1, sizeof(::operations_research::packing::vbp::VectorBinPackingSolution)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::operations_research::packing::vbp::_Item_default_instance_._instance,
  &::operations_research::packing::vbp::_VectorBinPackingProblem_default_instance_._instance,
  &::operations_research::packing::vbp::_VectorBinPackingOneBinInSolution_default_instance_._instance,
  &::operations_research::packing::vbp::_VectorBinPackingSolution_default_instance_._instance,
};

const char descriptor_table_protodef_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n(ortools/packing/vector_bin_packing.pro"
  "to\022\037operations_research.packing.vbp\"\245\001\n\004"
  "Item\022\014\n\004name\030\001 \001(\t\022\026\n\016resource_usage\030\002 \003"
  "(\003\022\022\n\nnum_copies\030\003 \001(\005\022\033\n\023num_optional_c"
  "opies\030\005 \001(\005\022$\n\034max_number_of_copies_per_"
  "bin\030\004 \001(\005\022 \n\030penalty_per_missing_copy\030\006 "
  "\001(\001\"\314\001\n\027VectorBinPackingProblem\022\014\n\004name\030"
  "\001 \001(\t\022\031\n\021resource_capacity\030\002 \003(\003\022\025\n\rreso"
  "urce_name\030\003 \003(\t\0223\n\004item\030\004 \003(\0132%.operatio"
  "ns_research.packing.vbp.Item\022\020\n\010max_bins"
  "\030\005 \001(\005\022\031\n\014cost_per_bin\030\006 \001(\001H\000\210\001\001B\017\n\r_co"
  "st_per_bin\"M\n VectorBinPackingOneBinInSo"
  "lution\022\024\n\014item_indices\030\001 \003(\005\022\023\n\013item_cop"
  "ies\030\002 \003(\005\"\250\002\n\030VectorBinPackingSolution\022\023"
  "\n\013solver_info\030\001 \001(\t\022O\n\004bins\030\002 \003(\0132A.oper"
  "ations_research.packing.vbp.VectorBinPac"
  "kingOneBinInSolution\022L\n\006status\030\003 \001(\0162<.o"
  "perations_research.packing.vbp.VectorBin"
  "PackingSolveStatus\022\027\n\017objective_value\030\004 "
  "\001(\001\022\035\n\025solve_time_in_seconds\030\005 \001(\001\022 \n\030ar"
  "c_flow_time_in_seconds\030\006 \001(\001*y\n\033VectorBi"
  "nPackingSolveStatus\022/\n+VECTOR_BIN_PACKIN"
  "G_SOLVE_STATUS_UNSPECIFIED\020\000\022\013\n\007OPTIMAL\020"
  "\001\022\014\n\010FEASIBLE\020\002\022\016\n\nINFEASIBLE\020\003B\?\n\036com.g"
  "oogle.ortools.packing.vbpP\001\252\002\032Google.OrT"
  "ools.Packing.Vbpb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto = {
    false, false, 1024, descriptor_table_protodef_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto,
    "ortools/packing/vector_bin_packing.proto",
    &descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto::offsets,
    file_level_metadata_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto, file_level_enum_descriptors_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto,
    file_level_service_descriptors_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto_getter() {
  return &descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto(&descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto);
namespace operations_research {
namespace packing {
namespace vbp {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* VectorBinPackingSolveStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto);
  return file_level_enum_descriptors_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto[0];
}
bool VectorBinPackingSolveStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Item::_Internal {
 public:
};

Item::Item(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:operations_research.packing.vbp.Item)
}
Item::Item(const Item& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Item* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_usage_){from._impl_.resource_usage_}
    , /*decltype(_impl_._resource_usage_cached_byte_size_)*/{0}
    , decltype(_impl_.name_){}
    , decltype(_impl_.num_copies_){}
    , decltype(_impl_.max_number_of_copies_per_bin_){}
    , decltype(_impl_.penalty_per_missing_copy_){}
    , decltype(_impl_.num_optional_copies_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.num_copies_, &from._impl_.num_copies_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.num_optional_copies_) -
    reinterpret_cast<char*>(&_impl_.num_copies_)) + sizeof(_impl_.num_optional_copies_));
  // @@protoc_insertion_point(copy_constructor:operations_research.packing.vbp.Item)
}

inline void Item::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_usage_){arena}
    , /*decltype(_impl_._resource_usage_cached_byte_size_)*/{0}
    , decltype(_impl_.name_){}
    , decltype(_impl_.num_copies_){0}
    , decltype(_impl_.max_number_of_copies_per_bin_){0}
    , decltype(_impl_.penalty_per_missing_copy_){0}
    , decltype(_impl_.num_optional_copies_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Item::~Item() {
  // @@protoc_insertion_point(destructor:operations_research.packing.vbp.Item)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Item::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.resource_usage_.~RepeatedField();
  _impl_.name_.Destroy();
}

void Item::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Item::Clear() {
// @@protoc_insertion_point(message_clear_start:operations_research.packing.vbp.Item)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.resource_usage_.Clear();
  _impl_.name_.ClearToEmpty();
  ::memset(&_impl_.num_copies_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.num_optional_copies_) -
      reinterpret_cast<char*>(&_impl_.num_copies_)) + sizeof(_impl_.num_optional_copies_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Item::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "operations_research.packing.vbp.Item.name"));
        } else
          goto handle_unusual;
        continue;
      // repeated int64 resource_usage = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt64Parser(_internal_mutable_resource_usage(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_resource_usage(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 num_copies = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.num_copies_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 max_number_of_copies_per_bin = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.max_number_of_copies_per_bin_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 num_optional_copies = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.num_optional_copies_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // double penalty_per_missing_copy = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.penalty_per_missing_copy_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Item::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:operations_research.packing.vbp.Item)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "operations_research.packing.vbp.Item.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // repeated int64 resource_usage = 2;
  {
    int byte_size = _impl_._resource_usage_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          2, _internal_resource_usage(), byte_size, target);
    }
  }

  // int32 num_copies = 3;
  if (this->_internal_num_copies() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_num_copies(), target);
  }

  // int32 max_number_of_copies_per_bin = 4;
  if (this->_internal_max_number_of_copies_per_bin() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_max_number_of_copies_per_bin(), target);
  }

  // int32 num_optional_copies = 5;
  if (this->_internal_num_optional_copies() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_num_optional_copies(), target);
  }

  // double penalty_per_missing_copy = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_penalty_per_missing_copy = this->_internal_penalty_per_missing_copy();
  uint64_t raw_penalty_per_missing_copy;
  memcpy(&raw_penalty_per_missing_copy, &tmp_penalty_per_missing_copy, sizeof(tmp_penalty_per_missing_copy));
  if (raw_penalty_per_missing_copy != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_penalty_per_missing_copy(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:operations_research.packing.vbp.Item)
  return target;
}

size_t Item::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:operations_research.packing.vbp.Item)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 resource_usage = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int64Size(this->_impl_.resource_usage_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._resource_usage_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // int32 num_copies = 3;
  if (this->_internal_num_copies() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_num_copies());
  }

  // int32 max_number_of_copies_per_bin = 4;
  if (this->_internal_max_number_of_copies_per_bin() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_max_number_of_copies_per_bin());
  }

  // double penalty_per_missing_copy = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_penalty_per_missing_copy = this->_internal_penalty_per_missing_copy();
  uint64_t raw_penalty_per_missing_copy;
  memcpy(&raw_penalty_per_missing_copy, &tmp_penalty_per_missing_copy, sizeof(tmp_penalty_per_missing_copy));
  if (raw_penalty_per_missing_copy != 0) {
    total_size += 1 + 8;
  }

  // int32 num_optional_copies = 5;
  if (this->_internal_num_optional_copies() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_num_optional_copies());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Item::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Item::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Item::GetClassData() const { return &_class_data_; }


void Item::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Item*>(&to_msg);
  auto& from = static_cast<const Item&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:operations_research.packing.vbp.Item)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.resource_usage_.MergeFrom(from._impl_.resource_usage_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_num_copies() != 0) {
    _this->_internal_set_num_copies(from._internal_num_copies());
  }
  if (from._internal_max_number_of_copies_per_bin() != 0) {
    _this->_internal_set_max_number_of_copies_per_bin(from._internal_max_number_of_copies_per_bin());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_penalty_per_missing_copy = from._internal_penalty_per_missing_copy();
  uint64_t raw_penalty_per_missing_copy;
  memcpy(&raw_penalty_per_missing_copy, &tmp_penalty_per_missing_copy, sizeof(tmp_penalty_per_missing_copy));
  if (raw_penalty_per_missing_copy != 0) {
    _this->_internal_set_penalty_per_missing_copy(from._internal_penalty_per_missing_copy());
  }
  if (from._internal_num_optional_copies() != 0) {
    _this->_internal_set_num_optional_copies(from._internal_num_optional_copies());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Item::CopyFrom(const Item& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:operations_research.packing.vbp.Item)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Item::IsInitialized() const {
  return true;
}

void Item::InternalSwap(Item* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.resource_usage_.InternalSwap(&other->_impl_.resource_usage_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Item, _impl_.num_optional_copies_)
      + sizeof(Item::_impl_.num_optional_copies_)
      - PROTOBUF_FIELD_OFFSET(Item, _impl_.num_copies_)>(
          reinterpret_cast<char*>(&_impl_.num_copies_),
          reinterpret_cast<char*>(&other->_impl_.num_copies_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Item::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto_getter, &descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto_once,
      file_level_metadata_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto[0]);
}

// ===================================================================

class VectorBinPackingProblem::_Internal {
 public:
  using HasBits = decltype(std::declval<VectorBinPackingProblem>()._impl_._has_bits_);
  static void set_has_cost_per_bin(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

VectorBinPackingProblem::VectorBinPackingProblem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:operations_research.packing.vbp.VectorBinPackingProblem)
}
VectorBinPackingProblem::VectorBinPackingProblem(const VectorBinPackingProblem& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VectorBinPackingProblem* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.resource_capacity_){from._impl_.resource_capacity_}
    , /*decltype(_impl_._resource_capacity_cached_byte_size_)*/{0}
    , decltype(_impl_.resource_name_){from._impl_.resource_name_}
    , decltype(_impl_.item_){from._impl_.item_}
    , decltype(_impl_.name_){}
    , decltype(_impl_.cost_per_bin_){}
    , decltype(_impl_.max_bins_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.cost_per_bin_, &from._impl_.cost_per_bin_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.max_bins_) -
    reinterpret_cast<char*>(&_impl_.cost_per_bin_)) + sizeof(_impl_.max_bins_));
  // @@protoc_insertion_point(copy_constructor:operations_research.packing.vbp.VectorBinPackingProblem)
}

inline void VectorBinPackingProblem::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.resource_capacity_){arena}
    , /*decltype(_impl_._resource_capacity_cached_byte_size_)*/{0}
    , decltype(_impl_.resource_name_){arena}
    , decltype(_impl_.item_){arena}
    , decltype(_impl_.name_){}
    , decltype(_impl_.cost_per_bin_){0}
    , decltype(_impl_.max_bins_){0}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

VectorBinPackingProblem::~VectorBinPackingProblem() {
  // @@protoc_insertion_point(destructor:operations_research.packing.vbp.VectorBinPackingProblem)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VectorBinPackingProblem::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.resource_capacity_.~RepeatedField();
  _impl_.resource_name_.~RepeatedPtrField();
  _impl_.item_.~RepeatedPtrField();
  _impl_.name_.Destroy();
}

void VectorBinPackingProblem::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VectorBinPackingProblem::Clear() {
// @@protoc_insertion_point(message_clear_start:operations_research.packing.vbp.VectorBinPackingProblem)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.resource_capacity_.Clear();
  _impl_.resource_name_.Clear();
  _impl_.item_.Clear();
  _impl_.name_.ClearToEmpty();
  _impl_.cost_per_bin_ = 0;
  _impl_.max_bins_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VectorBinPackingProblem::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "operations_research.packing.vbp.VectorBinPackingProblem.name"));
        } else
          goto handle_unusual;
        continue;
      // repeated int64 resource_capacity = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt64Parser(_internal_mutable_resource_capacity(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_resource_capacity(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string resource_name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_resource_name();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "operations_research.packing.vbp.VectorBinPackingProblem.resource_name"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .operations_research.packing.vbp.Item item = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_item(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // int32 max_bins = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.max_bins_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional double cost_per_bin = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _Internal::set_has_cost_per_bin(&has_bits);
          _impl_.cost_per_bin_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VectorBinPackingProblem::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:operations_research.packing.vbp.VectorBinPackingProblem)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "operations_research.packing.vbp.VectorBinPackingProblem.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // repeated int64 resource_capacity = 2;
  {
    int byte_size = _impl_._resource_capacity_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt64Packed(
          2, _internal_resource_capacity(), byte_size, target);
    }
  }

  // repeated string resource_name = 3;
  for (int i = 0, n = this->_internal_resource_name_size(); i < n; i++) {
    const auto& s = this->_internal_resource_name(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "operations_research.packing.vbp.VectorBinPackingProblem.resource_name");
    target = stream->WriteString(3, s, target);
  }

  // repeated .operations_research.packing.vbp.Item item = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_item_size()); i < n; i++) {
    const auto& repfield = this->_internal_item(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // int32 max_bins = 5;
  if (this->_internal_max_bins() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_max_bins(), target);
  }

  // optional double cost_per_bin = 6;
  if (_internal_has_cost_per_bin()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_cost_per_bin(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:operations_research.packing.vbp.VectorBinPackingProblem)
  return target;
}

size_t VectorBinPackingProblem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:operations_research.packing.vbp.VectorBinPackingProblem)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 resource_capacity = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int64Size(this->_impl_.resource_capacity_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._resource_capacity_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated string resource_name = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.resource_name_.size());
  for (int i = 0, n = _impl_.resource_name_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.resource_name_.Get(i));
  }

  // repeated .operations_research.packing.vbp.Item item = 4;
  total_size += 1UL * this->_internal_item_size();
  for (const auto& msg : this->_impl_.item_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // optional double cost_per_bin = 6;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + 8;
  }

  // int32 max_bins = 5;
  if (this->_internal_max_bins() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_max_bins());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VectorBinPackingProblem::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VectorBinPackingProblem::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VectorBinPackingProblem::GetClassData() const { return &_class_data_; }


void VectorBinPackingProblem::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VectorBinPackingProblem*>(&to_msg);
  auto& from = static_cast<const VectorBinPackingProblem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:operations_research.packing.vbp.VectorBinPackingProblem)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.resource_capacity_.MergeFrom(from._impl_.resource_capacity_);
  _this->_impl_.resource_name_.MergeFrom(from._impl_.resource_name_);
  _this->_impl_.item_.MergeFrom(from._impl_.item_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_has_cost_per_bin()) {
    _this->_internal_set_cost_per_bin(from._internal_cost_per_bin());
  }
  if (from._internal_max_bins() != 0) {
    _this->_internal_set_max_bins(from._internal_max_bins());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VectorBinPackingProblem::CopyFrom(const VectorBinPackingProblem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:operations_research.packing.vbp.VectorBinPackingProblem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VectorBinPackingProblem::IsInitialized() const {
  return true;
}

void VectorBinPackingProblem::InternalSwap(VectorBinPackingProblem* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.resource_capacity_.InternalSwap(&other->_impl_.resource_capacity_);
  _impl_.resource_name_.InternalSwap(&other->_impl_.resource_name_);
  _impl_.item_.InternalSwap(&other->_impl_.item_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VectorBinPackingProblem, _impl_.max_bins_)
      + sizeof(VectorBinPackingProblem::_impl_.max_bins_)
      - PROTOBUF_FIELD_OFFSET(VectorBinPackingProblem, _impl_.cost_per_bin_)>(
          reinterpret_cast<char*>(&_impl_.cost_per_bin_),
          reinterpret_cast<char*>(&other->_impl_.cost_per_bin_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VectorBinPackingProblem::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto_getter, &descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto_once,
      file_level_metadata_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto[1]);
}

// ===================================================================

class VectorBinPackingOneBinInSolution::_Internal {
 public:
};

VectorBinPackingOneBinInSolution::VectorBinPackingOneBinInSolution(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:operations_research.packing.vbp.VectorBinPackingOneBinInSolution)
}
VectorBinPackingOneBinInSolution::VectorBinPackingOneBinInSolution(const VectorBinPackingOneBinInSolution& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VectorBinPackingOneBinInSolution* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.item_indices_){from._impl_.item_indices_}
    , /*decltype(_impl_._item_indices_cached_byte_size_)*/{0}
    , decltype(_impl_.item_copies_){from._impl_.item_copies_}
    , /*decltype(_impl_._item_copies_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:operations_research.packing.vbp.VectorBinPackingOneBinInSolution)
}

inline void VectorBinPackingOneBinInSolution::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.item_indices_){arena}
    , /*decltype(_impl_._item_indices_cached_byte_size_)*/{0}
    , decltype(_impl_.item_copies_){arena}
    , /*decltype(_impl_._item_copies_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

VectorBinPackingOneBinInSolution::~VectorBinPackingOneBinInSolution() {
  // @@protoc_insertion_point(destructor:operations_research.packing.vbp.VectorBinPackingOneBinInSolution)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VectorBinPackingOneBinInSolution::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.item_indices_.~RepeatedField();
  _impl_.item_copies_.~RepeatedField();
}

void VectorBinPackingOneBinInSolution::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VectorBinPackingOneBinInSolution::Clear() {
// @@protoc_insertion_point(message_clear_start:operations_research.packing.vbp.VectorBinPackingOneBinInSolution)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.item_indices_.Clear();
  _impl_.item_copies_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VectorBinPackingOneBinInSolution::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated int32 item_indices = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_item_indices(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 8) {
          _internal_add_item_indices(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 item_copies = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_item_copies(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_item_copies(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VectorBinPackingOneBinInSolution::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:operations_research.packing.vbp.VectorBinPackingOneBinInSolution)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 item_indices = 1;
  {
    int byte_size = _impl_._item_indices_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          1, _internal_item_indices(), byte_size, target);
    }
  }

  // repeated int32 item_copies = 2;
  {
    int byte_size = _impl_._item_copies_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          2, _internal_item_copies(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:operations_research.packing.vbp.VectorBinPackingOneBinInSolution)
  return target;
}

size_t VectorBinPackingOneBinInSolution::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:operations_research.packing.vbp.VectorBinPackingOneBinInSolution)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 item_indices = 1;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.item_indices_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._item_indices_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated int32 item_copies = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.item_copies_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._item_copies_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VectorBinPackingOneBinInSolution::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VectorBinPackingOneBinInSolution::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VectorBinPackingOneBinInSolution::GetClassData() const { return &_class_data_; }


void VectorBinPackingOneBinInSolution::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VectorBinPackingOneBinInSolution*>(&to_msg);
  auto& from = static_cast<const VectorBinPackingOneBinInSolution&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:operations_research.packing.vbp.VectorBinPackingOneBinInSolution)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.item_indices_.MergeFrom(from._impl_.item_indices_);
  _this->_impl_.item_copies_.MergeFrom(from._impl_.item_copies_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VectorBinPackingOneBinInSolution::CopyFrom(const VectorBinPackingOneBinInSolution& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:operations_research.packing.vbp.VectorBinPackingOneBinInSolution)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VectorBinPackingOneBinInSolution::IsInitialized() const {
  return true;
}

void VectorBinPackingOneBinInSolution::InternalSwap(VectorBinPackingOneBinInSolution* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.item_indices_.InternalSwap(&other->_impl_.item_indices_);
  _impl_.item_copies_.InternalSwap(&other->_impl_.item_copies_);
}

::PROTOBUF_NAMESPACE_ID::Metadata VectorBinPackingOneBinInSolution::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto_getter, &descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto_once,
      file_level_metadata_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto[2]);
}

// ===================================================================

class VectorBinPackingSolution::_Internal {
 public:
};

VectorBinPackingSolution::VectorBinPackingSolution(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:operations_research.packing.vbp.VectorBinPackingSolution)
}
VectorBinPackingSolution::VectorBinPackingSolution(const VectorBinPackingSolution& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VectorBinPackingSolution* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.bins_){from._impl_.bins_}
    , decltype(_impl_.solver_info_){}
    , decltype(_impl_.objective_value_){}
    , decltype(_impl_.solve_time_in_seconds_){}
    , decltype(_impl_.arc_flow_time_in_seconds_){}
    , decltype(_impl_.status_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.solver_info_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.solver_info_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_solver_info().empty()) {
    _this->_impl_.solver_info_.Set(from._internal_solver_info(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.objective_value_, &from._impl_.objective_value_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.status_) -
    reinterpret_cast<char*>(&_impl_.objective_value_)) + sizeof(_impl_.status_));
  // @@protoc_insertion_point(copy_constructor:operations_research.packing.vbp.VectorBinPackingSolution)
}

inline void VectorBinPackingSolution::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.bins_){arena}
    , decltype(_impl_.solver_info_){}
    , decltype(_impl_.objective_value_){0}
    , decltype(_impl_.solve_time_in_seconds_){0}
    , decltype(_impl_.arc_flow_time_in_seconds_){0}
    , decltype(_impl_.status_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.solver_info_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.solver_info_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

VectorBinPackingSolution::~VectorBinPackingSolution() {
  // @@protoc_insertion_point(destructor:operations_research.packing.vbp.VectorBinPackingSolution)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VectorBinPackingSolution::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.bins_.~RepeatedPtrField();
  _impl_.solver_info_.Destroy();
}

void VectorBinPackingSolution::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VectorBinPackingSolution::Clear() {
// @@protoc_insertion_point(message_clear_start:operations_research.packing.vbp.VectorBinPackingSolution)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bins_.Clear();
  _impl_.solver_info_.ClearToEmpty();
  ::memset(&_impl_.objective_value_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.status_) -
      reinterpret_cast<char*>(&_impl_.objective_value_)) + sizeof(_impl_.status_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VectorBinPackingSolution::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string solver_info = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_solver_info();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "operations_research.packing.vbp.VectorBinPackingSolution.solver_info"));
        } else
          goto handle_unusual;
        continue;
      // repeated .operations_research.packing.vbp.VectorBinPackingOneBinInSolution bins = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_bins(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // .operations_research.packing.vbp.VectorBinPackingSolveStatus status = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::operations_research::packing::vbp::VectorBinPackingSolveStatus>(val));
        } else
          goto handle_unusual;
        continue;
      // double objective_value = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.objective_value_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double solve_time_in_seconds = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.solve_time_in_seconds_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // double arc_flow_time_in_seconds = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _impl_.arc_flow_time_in_seconds_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VectorBinPackingSolution::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:operations_research.packing.vbp.VectorBinPackingSolution)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string solver_info = 1;
  if (!this->_internal_solver_info().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_solver_info().data(), static_cast<int>(this->_internal_solver_info().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "operations_research.packing.vbp.VectorBinPackingSolution.solver_info");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_solver_info(), target);
  }

  // repeated .operations_research.packing.vbp.VectorBinPackingOneBinInSolution bins = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_bins_size()); i < n; i++) {
    const auto& repfield = this->_internal_bins(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // .operations_research.packing.vbp.VectorBinPackingSolveStatus status = 3;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      3, this->_internal_status(), target);
  }

  // double objective_value = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_objective_value = this->_internal_objective_value();
  uint64_t raw_objective_value;
  memcpy(&raw_objective_value, &tmp_objective_value, sizeof(tmp_objective_value));
  if (raw_objective_value != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_objective_value(), target);
  }

  // double solve_time_in_seconds = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_solve_time_in_seconds = this->_internal_solve_time_in_seconds();
  uint64_t raw_solve_time_in_seconds;
  memcpy(&raw_solve_time_in_seconds, &tmp_solve_time_in_seconds, sizeof(tmp_solve_time_in_seconds));
  if (raw_solve_time_in_seconds != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_solve_time_in_seconds(), target);
  }

  // double arc_flow_time_in_seconds = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_arc_flow_time_in_seconds = this->_internal_arc_flow_time_in_seconds();
  uint64_t raw_arc_flow_time_in_seconds;
  memcpy(&raw_arc_flow_time_in_seconds, &tmp_arc_flow_time_in_seconds, sizeof(tmp_arc_flow_time_in_seconds));
  if (raw_arc_flow_time_in_seconds != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_arc_flow_time_in_seconds(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:operations_research.packing.vbp.VectorBinPackingSolution)
  return target;
}

size_t VectorBinPackingSolution::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:operations_research.packing.vbp.VectorBinPackingSolution)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .operations_research.packing.vbp.VectorBinPackingOneBinInSolution bins = 2;
  total_size += 1UL * this->_internal_bins_size();
  for (const auto& msg : this->_impl_.bins_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string solver_info = 1;
  if (!this->_internal_solver_info().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_solver_info());
  }

  // double objective_value = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_objective_value = this->_internal_objective_value();
  uint64_t raw_objective_value;
  memcpy(&raw_objective_value, &tmp_objective_value, sizeof(tmp_objective_value));
  if (raw_objective_value != 0) {
    total_size += 1 + 8;
  }

  // double solve_time_in_seconds = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_solve_time_in_seconds = this->_internal_solve_time_in_seconds();
  uint64_t raw_solve_time_in_seconds;
  memcpy(&raw_solve_time_in_seconds, &tmp_solve_time_in_seconds, sizeof(tmp_solve_time_in_seconds));
  if (raw_solve_time_in_seconds != 0) {
    total_size += 1 + 8;
  }

  // double arc_flow_time_in_seconds = 6;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_arc_flow_time_in_seconds = this->_internal_arc_flow_time_in_seconds();
  uint64_t raw_arc_flow_time_in_seconds;
  memcpy(&raw_arc_flow_time_in_seconds, &tmp_arc_flow_time_in_seconds, sizeof(tmp_arc_flow_time_in_seconds));
  if (raw_arc_flow_time_in_seconds != 0) {
    total_size += 1 + 8;
  }

  // .operations_research.packing.vbp.VectorBinPackingSolveStatus status = 3;
  if (this->_internal_status() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VectorBinPackingSolution::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VectorBinPackingSolution::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VectorBinPackingSolution::GetClassData() const { return &_class_data_; }


void VectorBinPackingSolution::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VectorBinPackingSolution*>(&to_msg);
  auto& from = static_cast<const VectorBinPackingSolution&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:operations_research.packing.vbp.VectorBinPackingSolution)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.bins_.MergeFrom(from._impl_.bins_);
  if (!from._internal_solver_info().empty()) {
    _this->_internal_set_solver_info(from._internal_solver_info());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_objective_value = from._internal_objective_value();
  uint64_t raw_objective_value;
  memcpy(&raw_objective_value, &tmp_objective_value, sizeof(tmp_objective_value));
  if (raw_objective_value != 0) {
    _this->_internal_set_objective_value(from._internal_objective_value());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_solve_time_in_seconds = from._internal_solve_time_in_seconds();
  uint64_t raw_solve_time_in_seconds;
  memcpy(&raw_solve_time_in_seconds, &tmp_solve_time_in_seconds, sizeof(tmp_solve_time_in_seconds));
  if (raw_solve_time_in_seconds != 0) {
    _this->_internal_set_solve_time_in_seconds(from._internal_solve_time_in_seconds());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_arc_flow_time_in_seconds = from._internal_arc_flow_time_in_seconds();
  uint64_t raw_arc_flow_time_in_seconds;
  memcpy(&raw_arc_flow_time_in_seconds, &tmp_arc_flow_time_in_seconds, sizeof(tmp_arc_flow_time_in_seconds));
  if (raw_arc_flow_time_in_seconds != 0) {
    _this->_internal_set_arc_flow_time_in_seconds(from._internal_arc_flow_time_in_seconds());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VectorBinPackingSolution::CopyFrom(const VectorBinPackingSolution& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:operations_research.packing.vbp.VectorBinPackingSolution)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VectorBinPackingSolution::IsInitialized() const {
  return true;
}

void VectorBinPackingSolution::InternalSwap(VectorBinPackingSolution* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.bins_.InternalSwap(&other->_impl_.bins_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.solver_info_, lhs_arena,
      &other->_impl_.solver_info_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VectorBinPackingSolution, _impl_.status_)
      + sizeof(VectorBinPackingSolution::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(VectorBinPackingSolution, _impl_.objective_value_)>(
          reinterpret_cast<char*>(&_impl_.objective_value_),
          reinterpret_cast<char*>(&other->_impl_.objective_value_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VectorBinPackingSolution::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto_getter, &descriptor_table_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto_once,
      file_level_metadata_ortools_2fpacking_2fvector_5fbin_5fpacking_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace vbp
}  // namespace packing
}  // namespace operations_research
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::operations_research::packing::vbp::Item*
Arena::CreateMaybeMessage< ::operations_research::packing::vbp::Item >(Arena* arena) {
  return Arena::CreateMessageInternal< ::operations_research::packing::vbp::Item >(arena);
}
template<> PROTOBUF_NOINLINE ::operations_research::packing::vbp::VectorBinPackingProblem*
Arena::CreateMaybeMessage< ::operations_research::packing::vbp::VectorBinPackingProblem >(Arena* arena) {
  return Arena::CreateMessageInternal< ::operations_research::packing::vbp::VectorBinPackingProblem >(arena);
}
template<> PROTOBUF_NOINLINE ::operations_research::packing::vbp::VectorBinPackingOneBinInSolution*
Arena::CreateMaybeMessage< ::operations_research::packing::vbp::VectorBinPackingOneBinInSolution >(Arena* arena) {
  return Arena::CreateMessageInternal< ::operations_research::packing::vbp::VectorBinPackingOneBinInSolution >(arena);
}
template<> PROTOBUF_NOINLINE ::operations_research::packing::vbp::VectorBinPackingSolution*
Arena::CreateMaybeMessage< ::operations_research::packing::vbp::VectorBinPackingSolution >(Arena* arena) {
  return Arena::CreateMessageInternal< ::operations_research::packing::vbp::VectorBinPackingSolution >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
